### ISSUE TITLE
Hydrate overrwrite initial state without merge

### ISSUE THREAD

**Issue by Biromain** [natural-apptitude/ngrx-store-ionic-storage#7]
With ngrx/platform, we can define [initial state](https://github.com/ngrx/platform/blob/master/docs/store/api.md#initial-state) but storageSync seem overwrite it.

**Comment by emcniece** [comment]
This is problematic for me during "upgrades", or when I change/add store data between versions - I have to perform state checks in my reducers because `initialState` gets trampled by hydration.

If v0.1 has a model stored and v0.2 changes this model, hydration results in the v0.1 model _without_ the v0.2 defaults.

Kinda sounds like this library should be doing an `Object.assign()` instead of a direct `=`.

**Comment by joewoodhouse** [comment]
Library now does Object.assign() in 4.2.0

**Comment by BDominik** [comment]
This is still not working for me with 4.2.
